# Generated by Django 3.0.3 on 2020-02-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exmaple2',
            new_name='Example2',
        ),
    ]
